import { parseArgs } from "node:util";
import { getUserByEmail } from "@/db/queries/users";
import { getSyntheticFixtureSafetyForUser } from "@/db/queries/synthetic-fixtures";
import { insertHealthSamples } from "@/db/queries/health-samples";
import { getConsentForUser, getPreferencesForUser, saveCheckInForUser, saveManualLogForUser, updateConsentForUser, updatePreferencesForUser } from "@/db/queries/product-state";
import { saveTrainingSessionForUser } from "@/db/queries/training-sessions";
import type { TrainingSession } from "@/lib/contracts";

const SOURCE = "BRIO synthetic test generator";
const VERSION = "brio-app-fixture-v2";

function parse() {
  const { values } = parseArgs({ options: { email: { type: "string" }, userId: { type: "string" }, days: { type: "string", default: "14" }, confirmSynthetic: { type: "boolean", default: false }, allowMixedAccount: { type: "boolean", default: false } } });
  if (!values.confirmSynthetic) throw new Error("Synthetic generation requires --confirmSynthetic. Use only with a dedicated test account.");
  const days = Math.min(60, Math.max(7, Number(values.days)));
  if (!Number.isFinite(days)) throw new Error("--days must be a number");
  return { email: values.email, userId: values.userId, days, allowMixedAccount: values.allowMixedAccount };
}

function dateKey(date: Date) { return date.toISOString().slice(0, 10); }
function isoAt(daysAgo: number, hour: number) { const date = new Date(); date.setUTCDate(date.getUTCDate() - daysAgo); date.setUTCHours(hour, 0, 0, 0); return date; }
function wave(day: number, base: number, spread: number) { return Math.round((base + Math.sin(day * 1.7) * spread) * 10) / 10; }

function sessionFor(userId: string, daysAgo: number): Omit<TrainingSession, "createdAt" | "updatedAt"> {
  const start = isoAt(daysAgo, 17); const end = new Date(start.getTime() + 55 * 60 * 1000); const key = dateKey(start);
  const exercise = (name: string, exerciseIndex: number, load: number, reps: number) => ({ id: `${userId}-${key}-exercise-${exerciseIndex}`, order: exerciseIndex, name, notes: "[SYNTHETIC INPUT] Comparable history fixture.", sets: [0, 1, 2].map((index) => ({ id: `${userId}-${key}-exercise-${exerciseIndex}-set-${index}`, order: index, type: index === 0 ? "warm_up" as const : "working" as const, loadKg: index === 0 ? Math.round(load * .55) : load, reps: index === 0 ? reps + 3 : reps, rpe: index === 0 ? null : 6.5 + (daysAgo % 3) * .5, notes: "[SYNTHETIC INPUT]", completed: true, completedAt: new Date(start.getTime() + (exerciseIndex * 20 + index * 4 + 5) * 60 * 1000).toISOString(), restStartedAt: null, restDurationSeconds: index === 0 ? 75 : 120, restPausedRemainingSeconds: null })) });
  return { schemaVersion: "1.0.0", id: `synthetic-session-${key}`, title: `[SYNTHETIC INPUT] Strength ${key}`, status: "completed", inputDataMode: "synthetic_input", startedAt: start.toISOString(), endedAt: end.toISOString(), exercises: [exercise("Back squat", 0, wave(daysAgo, 78, 4), 5), exercise("Romanian deadlift", 1, wave(daysAgo, 62, 3), 8)], notes: `[SYNTHETIC INPUT] Generated by ${VERSION}; not a real session.`, revision: 0, mutationId: `synthetic-session-${key}-v2` };
}

async function main() {
  const args = parse();
  const user = args.userId ? { id: args.userId, email: "user-id target" } : args.email ? await getUserByEmail(args.email) : null;
  if (!user) throw new Error("Pass an existing --email or --userId for a dedicated test account");
  const safety = await getSyntheticFixtureSafetyForUser(user.id);
  if (!safety.safe && !args.allowMixedAccount) throw new Error(`Refusing to mix synthetic fixtures with ${safety.realRecordCount} non-synthetic records. Use a dedicated account or explicitly add --allowMixedAccount.`);
  console.log(`[SYNTHETIC INPUT] Target ${user.email}; generator ${VERSION}; days ${args.days}; mixed override ${Boolean(args.allowMixedAccount)}.`);

  let preferences = await getPreferencesForUser(user.id);
  if (!preferences.profile.completed) preferences = await updatePreferencesForUser(user.id, { revision: preferences.revision, mutationId: `synthetic-profile-${VERSION}`, profile: { birthYear: 1993, sex: "prefer_not_to_say", activityLevel: "moderate", trainingExperience: "one_to_three_years", primaryTraining: "strength", trainingDaysPerWeek: 4, typicalSessionMinutes: 55, recentTrainingSummary: "[SYNTHETIC INPUT] Four strength sessions weekly for the last eight weeks.", equipmentAccess: "[SYNTHETIC INPUT] Barbell, rack, plates and dumbbells.", completed: true }, onboardingCompleted: true });

  const consent = await getConsentForUser(user.id);
  const fixtureSignals = ["health_steps", "health_active_energy", "health_heart_rate", "health_sleep", "manual_training", "manual_nutrition", "daily_check_in"] as const;
  const missingSignals = fixtureSignals.filter((signal) => !consent.signals.find((item) => item.signal === signal)?.enabled);
  if (missingSignals.length) await updateConsentForUser(user.id, { expectedConsentVersion: consent.consentVersion, mutationId: `synthetic-consent-${crypto.randomUUID()}`, changes: missingSignals.map((signal) => ({ signal, enabled: true })) });

  const healthRows: Parameters<typeof insertHealthSamples>[0] = [];
  for (let daysAgo = 0; daysAgo < args.days; daysAgo++) {
    const date = isoAt(daysAgo, 0); const key = dateKey(date);
    const bedtime = isoAt(daysAgo + 1, 23); const wake = new Date(bedtime.getTime() + wave(daysAgo, 7.2, .5) * 3600 * 1000);
    healthRows.push({ userId: user.id, externalId: `${VERSION}:${key}:sleep`, sampleType: "HKCategoryTypeIdentifierSleepAnalysis", value: 1, unit: null, startDate: bedtime, endDate: wake, sourceName: SOURCE, metadata: { synthetic: true, generatorVersion: VERSION, outcome: "synthetic_input" } });
    healthRows.push({ userId: user.id, externalId: `${VERSION}:${key}:steps`, sampleType: "HKQuantityTypeIdentifierStepCount", value: wave(daysAgo, 8200, 1400), unit: "count", startDate: isoAt(daysAgo, 8), endDate: isoAt(daysAgo, 21), sourceName: SOURCE, metadata: { synthetic: true, generatorVersion: VERSION } });
    healthRows.push({ userId: user.id, externalId: `${VERSION}:${key}:energy`, sampleType: "HKQuantityTypeIdentifierActiveEnergyBurned", value: wave(daysAgo, 520, 90), unit: "kcal", startDate: isoAt(daysAgo, 8), endDate: isoAt(daysAgo, 21), sourceName: SOURCE, metadata: { synthetic: true, generatorVersion: VERSION } });
    for (const hour of [8, 12, 16, 20]) healthRows.push({ userId: user.id, externalId: `${VERSION}:${key}:hr:${hour}`, sampleType: "HKQuantityTypeIdentifierHeartRate", value: wave(daysAgo + hour, 69, 8), unit: "count/min", startDate: isoAt(daysAgo, hour), endDate: isoAt(daysAgo, hour), sourceName: SOURCE, metadata: { synthetic: true, generatorVersion: VERSION } });
  }
  const insertedHealth = await insertHealthSamples(healthRows);
  for (const daysAgo of [10, 7, 4, 1]) await saveTrainingSessionForUser(user.id, sessionFor(user.id, daysAgo));
  const today = dateKey(new Date());
  await saveManualLogForUser(user.id, { schemaVersion: "1.0.0", localDate: today, overall: { note: `[SYNTHETIC INPUT] ${VERSION}` }, nutrition: { energyIntakeKcal: 2380, proteinGrams: 148, carbohydrateGrams: 262, fatGrams: 72 }, mutationId: `synthetic-manual-${today}`, revision: 0, recordedAt: new Date().toISOString() });
  await saveCheckInForUser(user.id, { schemaVersion: "1.0.0", localDate: today, responses: [{ key: "fatigue", rating: 3 }, { key: "muscle_soreness", rating: 2 }, { key: "sleep_quality", rating: 4 }, { key: "stress", rating: 2 }, { key: "mood", rating: 4 }], mutationId: `synthetic-checkin-${today}`, revision: 0, recordedAt: new Date().toISOString() });
  console.log(`[SYNTHETIC INPUT] Upserted ${insertedHealth.length} labelled health records, four comparable sessions, today's nutrition, check-in and profile. Server AI consent remains off.`);
}

main().then(() => process.exit(0)).catch((error) => { console.error(error instanceof Error ? error.message : error); process.exit(1); });
