import Link from "next/link";
import { requireUser } from "@/db/auth-dal";
import { listTrainingSessionsForUser } from "@/db/queries/training-sessions";
import { getLatestDecisionForUser } from "@/db/queries/decisions";
import { TrainingAnalytics } from "@/components/training-analytics";

export default async function TrainingPage() {
  const user = await requireUser();
  const [sessions, decision] = await Promise.all([listTrainingSessionsForUser(user.id), getLatestDecisionForUser(user.id)]);
  return <div className="page-shell"><div className="page-head"><div><span className="eyebrow">Training</span><h1 className="page-title">Start from a saved record, your description, or plans.</h1><p className="page-subtitle">Manual records and recommendation context stay distinct. Nothing is silently prescribed or committed.</p></div></div>
    {decision && <section className={`card ${decision.action === "Escalate" ? "critical" : "mist"}`} style={{ marginBottom: 20 }}><span className="eyebrow">Latest bounded proposed action · not applied</span><div className="split"><div><h2 className="section-title">{decision.action}</h2><p className="muted">{decision.proposal.text}</p></div><Link href="/dashboard" className="button button-secondary">Inspect decision</Link></div>{decision.action === "Escalate" && <p className="status-escalate"><strong>No prescribed session may be generated from an Escalate action.</strong> User-entered historical and session logging remain available as records.</p>}</section>}
    <section className="entry-grid"><div className="card"><span className="eyebrow">1 · Start a saved session</span><h2 className="section-title">{sessions.length ? `${sessions.length} saved session${sessions.length === 1 ? "" : "s"}` : "No saved sessions"}</h2><p className="muted">Drafts and active sessions persist across reloads with revision checks.</p>{sessions.length > 0 ? <div className="stack-tight" style={{ marginTop: 16 }}>{sessions.slice(0, 6).map((session) => <Link className="saved-session-link" href={`/training/${session.id}`} key={session.id}><span><strong>{session.title}</strong><small>{session.exercises.length} exercises · {new Date(session.updatedAt).toLocaleString("en-IE")}</small></span><span className="status-word">{session.status}</span></Link>)}</div> : <div className="empty-state compact" style={{ marginTop: 16 }}><p className="muted small">Describe a session to create a reviewed draft.</p></div>}</div><div className="card mist"><span className="eyebrow">2 · Describe it</span><h2 className="section-title">Structure your own session.</h2><p className="muted">A transparent deterministic parser creates a fully editable, unsaved interpretation. You must review it before saving.</p><Link href="/training/describe" className="button">Describe a session</Link></div><div className="card"><span className="eyebrow">3 · Browse plans</span><h2 className="section-title">P2 deferred</h2><p className="muted">Open the explicit deferred state. No catalogue or specialist execution is implied.</p><Link href="/training/plans" className="button button-secondary">Browse plans</Link></div></section>
    <div className="cluster" style={{ margin: "18px 0 30px" }}><Link href="/training/new" className="text-link">Create a blank session</Link><span className="muted">·</span><Link href="/training/new?mode=historical" className="text-link">Log a historical session</Link></div><TrainingAnalytics sessions={sessions}/>
  </div>;
}
